#!/bin/bash -l

#SBATCH --job-name pose6d-training
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 32
#SBATCH --mem 92GB
#SBATCH --time 72:00:00
#SBATCH --partition=h100
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --output /home/sibwang/poseforge/scripts_on_cluster/pose6d_training/output_20251211a.log

echo "Hello from $(hostname)"

. ~/spack/share/spack/setup-env.sh
spack load ffmpeg
conda activate poseforge
cd $HOME/poseforge

training_cli_path="src/poseforge/pose/pose6d/scripts/run_training.py"
training_trial_name="20251211a"
contrastive_pretraining_trial_name="trial_20251125a_lowlr"
contrastive_pretraining_epoch="epoch009"
contrastive_pretraining_local_step="step003055"

echo "Training starting at $(date)"

python -u $training_cli_path \
    --n_epochs 15 \
    --seed 42 \
    --model-architecture-config.n-segments 25 \
    --model-architecture-config.n-attention-gated-feature-channels 192 \
    --model-architecture-config.n-global-feature-channels 64 \
    --model-architecture-config.camera-distance 100.0 \
    --model-weights-config.feature-extractor-weights \
        "bulk_data/pose_estimation/contrastive_pretraining/$contrastive_pretraining_trial_name/checkpoints/checkpoint_${contrastive_pretraining_epoch}_${contrastive_pretraining_local_step}.feature_extractor.pth" \
    --loss-config.translation-weight 1.0 \
    --loss-config.rotation-weight 10.0 \
    --training-data-config.train-data-dirs \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly1_trial001" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly1_trial002" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly1_trial003" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly1_trial004" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly1_trial005" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly2_trial001" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly2_trial002" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly2_trial003" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly2_trial004" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly2_trial005" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly3_trial001" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly3_trial002" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly3_trial003" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly3_trial004" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly3_trial005" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly4_trial001" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly4_trial002" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly4_trial003" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly4_trial004" \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly4_trial005" \
    --training-data-config.val-data-dirs \
        "bulk_data/pose_estimation/atomic_batches/4variants/BO_Gal4_fly5_trial001" \
    --training-data-config.input-image-size 256 256 \
    --training-data-config.atomic-batch-n-samples 32 \
    --training-data-config.atomic-batch-n-variants 4 \
    --training-data-config.train-batch-size 128 \
    --training-data-config.val-batch-size 512 \
    --training-data-config.n-workers 8 \
    --optimizer-config.learning_rate_encoder 0.0001 \
    --optimizer-config.learning_rate_upsample 0.001 \
    --optimizer-config.learning_rate_attention 0.001 \
    --optimizer-config.learning_rate_pose6d_heads 0.001 \
    --optimizer-config.weight-decay 0.00001 \
    --training-artifacts-config.output-basedir \
        "bulk_data/pose_estimation/pose6d/$training_trial_name/" \
    --training-artifacts-config.logging-interval 10 \
    --training-artifacts-config.checkpoint-interval 1000 \
    --training-artifacts-config.validation-interval 300 \
    --training-artifacts-config.n-batches-per-validation 30

echo "Training ends at $(date)"
