flip_detection:
  checkpoint: "~/projects/poseforge/production_models/flip_detection/v1/production_checkpoint_v1.pth"
  working_size: 224
  init_params:
    input_channels: 1
    num_classes: 2
  output_labels: ["not_flipped", "flipped"]

bodyseg:
  checkpoint: "~/projects/poseforge/production_models/bodyseg/v2/production_checkpoint.model.pth"
  architecture_config: "~/projects/poseforge/production_models/bodyseg/v2/configs/model_architecture_config.yaml"
  working_size: 256
  n_classes: 29
  output_labels: [
    "Background", "OtherSegments", "Thorax",
    "LFCoxa", "LFFemur", "LFTibia", "LFTarsus",
    "LMCoxa", "LMFemur", "LMTibia", "LMTarsus",
    "LHCoxa", "LHFemur", "LHTibia", "LHTarsus",
    "RFCoxa", "RFFemur", "RFTibia", "RFTarsus",
    "RMCoxa", "RMFemur", "RMTibia", "RMTarsus",
    "RHCoxa", "RHFemur", "RHTibia", "RHTarsus",
    "LAntenna", "RAntenna"
  ]

keypoints3d:
  checkpoint: "~/projects/poseforge/production_models/keypoints3d/v2/production_checkpoint.model.pth"
  architecture_config: "~/projects/poseforge/production_models/keypoints3d/v2/configs/model_architecture_config.yaml"
  working_size: 256
  n_keypoints: -1
  keypoint_names: [
    "LFThC", "LFCTr", "LFFTi", "LFTiTa", "LFClaw",
    "LMThC", "LMCTr", "LMFTi", "LMTiTa", "LMClaw",
    "LHThC", "LHCTr", "LHFTi", "LHTiTa", "LHClaw",
    "RFThC", "RFCTr", "RFFTi", "RFTiTa", "RFClaw",
    "RMThC", "RMCTr", "RMFTi", "RMTiTa", "RMClaw",
    "RHThC", "RHCTr", "RHFTi", "RHTiTa", "RHClaw",
    "LPedicel", "RPedicel"
  ]