from pathlib import Path
from dataclasses import dataclass
from loguru import logger


@dataclass
class SpotlightRecordingPaths:
    """Dataclass containing all file paths for a Spotlight recording with validation.

    This class handles the initialization of all file paths required for processing
    a Spotlight recording and validates that the required files exist. It provides
    a clean separation between path management and the main processing logic.

    Attributes:
        data_path: Base path to the recording data directory
        with_muscle: Whether muscle data is expected to be available
        muscle_available: Whether muscle data files are actually available (set after
            validation)
        (see below for automatically derived paths)

    Paths to metadata generated by the Spotlight recorder (not including metadata
    generated during postprocessing):
        - recorder_metadata_dir (dir):
            Base directory containing such metadata files
        - recorder_config (YAML):
            `recorder_config.yaml` file used by the Spotlight recorder for this trial
        - behavior_cam_calib (YAML):
            Behavior camera calibration parameters (i.e. affine transforms for mapping
            between behavior camera, stage, and physical coords)
        - experiment_param (YAML):
            Settings set in the Spotlight recorder GUI
        - dual_recording_timing_config (YAML, only if with muscle):
            Information on synchronization between behavior and muscle cameras
        - muscle_cam_calib (YAML, only if with muscle):
            Muscle camera calibration parameters (i.e. affine transforms for mapping
            between muscle camera, stage, and physical coords)

    Paths to processed data generated by `spotlight_tools.postprocessing`:
        - processed_dir (dir):
            Base directory containing such processed data
        - aligned_behavior_video (MKV):
            Aligned behavior video file
        - alignment_metadata (HDF5):
            Parameters for transforms applied to align the fly, including simple
            2D pose predicted by a SLEAP model (3 keypoints only). This was used to
            determine the fly's orientation and position, which were then used to align
            the frames
        - behavior_frames_metadata (CSV):
            Metadata for each behavior frame, including timing information (acquisition
            time, etc.) and stage positions at the time of each behavior frame
            interpolated from the raw stage tracking log
        - aligned_muscle_frames_dir (dir, only if with muscle):
            Directory containing aligned muscle images (individual TIFF files)
        - muscle_frames_metadata (CSV, only if with muscle):
            Metadata for each muscle frame, including timing information (acquisition
            time, etc.) and stage positions at the time of each muscle frame
            interpolated from the raw stage tracking log

    Paths to output files to be generated by the poseforge production pipeline:
        - output_dir (dir):
            Base directory for such output files
        - usable_frames (CSV):
            Metadata on which behavior frames are usable based on (1) whether the fly
            is flipped and (2) whether any keypoint is too close to the arena edge.
        - keypoints3d_prediction (HDF5):
            3D keypoint model predictions
        - invkin_output (HDF5):
            Inverse kinematics solution and forward kinematics reconstructions
        - bodyseg_prediction (HDF5):
            Body segmentation model predictions
        - keypoints3d_viz (MP4):
            Visualization video for 3D keypoint predictions, including inverse and
            forward kinematics
        - bodyseg_viz (MP4):
            Visualization video for body segmentation predictions

    Raises:
        FileNotFoundError: If required files are missing during validation
    """

    trial_basedir: Path
    with_muscle: bool = False

    def __post_init__(self):
        """Initialize derived paths and validate required files."""
        # Convert to Path if string
        self.trial_basedir = Path(self.trial_basedir)

        # Metadata paths - from Spotlight recorder
        self.recorder_metadata_dir = self.trial_basedir / "metadata/"
        _metadir = self.recorder_metadata_dir
        self.recorder_config = _metadir / "recorder_config.yaml"
        self.behavior_cam_calib = _metadir / "calibration_parameters_behavior.yaml"
        self.experiment_param = _metadir / "experiment_parameters.yaml"
        if self.with_muscle:
            self.dual_recording_timing_config = _metadir / "dual_recording_timing.yaml"
            self.muscle_cam_calib = _metadir / "calibration_parameters_muscle.yaml"
        else:
            self.dual_recording_timing_config = None
            self.muscle_cam_calib = None

        # Processed paths - from spotlight_tools.postprocessing
        self.processed_dir = self.trial_basedir / "processed/"
        _procdir = self.processed_dir
        self.aligned_behavior_video = _procdir / "aligned_behavior_video.mkv"
        self.alignment_metadata = _procdir / "behavior_alignment_transforms.h5"
        self.behavior_frames_metadata = _procdir / "behavior_frames_metadata.csv"
        if self.with_muscle:
            self.aligned_muscle_frames_dir = _procdir / "aligned_muscle_images/"
            self.muscle_frames_metadata = _procdir / "muscle_frames_metadata.csv"
        else:
            self.aligned_muscle_frames_dir = None
            self.muscle_frames_metadata = None

        # Check if required files exist
        required_behavior_path_attrs = [
            "recorder_config",
            "behavior_cam_calib",
            "experiment_param",
            "aligned_behavior_video",
            "alignment_metadata",
            "behavior_frames_metadata",
        ]
        required_muscle_path_attrs = [
            "dual_recording_timing_config",
            "muscle_cam_calib",
            "aligned_muscle_frames_dir",
            "muscle_frames_metadata",
        ]
        if not self._check_paths_exist(required_behavior_path_attrs):
            raise FileNotFoundError(
                "One or more generally required data files are missing."
            )
        if self.with_muscle and not self._check_paths_exist(required_muscle_path_attrs):
            raise FileNotFoundError(
                "with_muscle is set to True but one or more required muscle data files "
                "are missing."
            )

        # Output - to be generated by this module
        self.output_dir = self.trial_basedir / "poseforge_output/"
        _outdir = self.output_dir
        _outdir.mkdir(parents=True, exist_ok=True)
        self.usable_frames = _outdir / "usable_frames.csv"
        self.keypoints3d_prediction = _outdir / "keypoints3d_prediction.h5"
        self.invkin_output = _outdir / "inverse_kinematics_output.h5"
        self.keypoints3d_viz = _outdir / "keypoints3d_viz.mp4"
        self.bodyseg_prediction = _outdir / "bodyseg_prediction.h5"
        self.bodyseg_viz = _outdir / "bodyseg_viz.mp4"

    def _check_paths_exist(self, required_path_attrs: list[str]) -> bool:
        for path_attr in required_path_attrs:
            if not hasattr(self, path_attr):
                raise AttributeError(
                    f"Input object does not have attribute '{path_attr}'"
                )
            path = getattr(self, path_attr)
            if not path.exists():
                logger.error(f"Required file '{path_attr}' doesn't exist: {path}")
                return False
        return True
