#!/bin/bash -l

#SBATCH --job-name contrastive_pretraining
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 16
#SBATCH --mem 75GB
#SBATCH --time 48:00:00
#SBATCH --partition=h100
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --output /home/sibwang/biomechpose/scripts_on_cluster/contrastive_pretraining_training/output.log

echo "Hello from $(hostname)"

conda activate biomechpose

cd /home/sibwang/biomechpose
echo "Training starting at $(date)"

trial_name="trial_20251001a"

python -u src/biomechpose/pose_estimation/scripts/run_contrastive_pretraining.py \
    --sampling.atomic-batch-nsamples 32 \
    --sampling.atomic-batch-nvariants 4 \
    --sampling.train-batch-size 960 \
    --sampling.val-batch-size 256 \
    --sampling.num-workers 4 \
    --model.use-pretrained-backbone \
    --model.projection-head-hidden-dim 512 \
    --model.projection-head-output-dim 256 \
    --data.train-data-dirs \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial005" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial005" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial005" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial005" \
    --data.val-data-dirs \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
    --data.image-size 256 256 \
    --data.num-channels 3 \
    --training.num-epochs 10 \
    --training.seed 42 \
    --training.adam-lr 3e-4 \
    --training.adam-weight-decay 1e-4 \
    --output.output-basedir \
        "bulk_data/pose_estimation/contrastive_pretraining/$trial_name" \
    --output.logging-interval 10 \
    --output.checkpoint-interval 200 \
    --output.validation-interval 200 \
    --output.nbatches-per-validation 100

echo "Training ends at $(date)"
