#!/bin/bash -l

#SBATCH --job-name contrastive_pretraining
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 16
#SBATCH --mem 75GB
#SBATCH --time 48:00:00
#SBATCH --partition=h100
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --output /home/sibwang/poseforge/scripts_on_cluster/contrastive_pretraining_training/output.log

echo "Hello from $(hostname)"

spack load ffmpeg
conda activate poseforge

cd $HOME/poseforge
echo "Training starting at $(date)"

trial_name="trial_20251011a"

python -u src/poseforge/pose_estimation/contrast/scripts/run_contrastive_pretraining.py \
    --n-epochs 10 \
    --seed 42 \
    --model-architecture-config.projection-head-hidden-dim 512 \
    --model-architecture-config.projection-head-output-dim 256 \
    --model-weights-config.feature-extractor-weights "IMAGENET1K_V1" \
    --loss-config.info-nce-temperature 0.1 \
    --training-data-config.train-data-dirs \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial005" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial005" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial005" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial001" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial002" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial003" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial004" \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial005" \
    --training-data-config.val-data-dirs \
        "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
    --training-data-config.atomic-batch-n-samples 32 \
    --training-data-config.atomic-batch-n-variants 4 \
    --training-data-config.train-batch-size 960 \
    --training-data-config.val-batch-size 256 \
    --training-data-config.image-size 256 256 \
    --training-data-config.n-workers 12 \
    --optimizer-config.adam-lr 3e-4 \
    --optimizer-config.adam-weight-decay 1e-4 \
    --training-artifacts-config.output-basedir \
        "bulk_data/pose_estimation/contrastive_pretraining/$trial_name" \
    --training-artifacts-config.logging-interval 10 \
    --training-artifacts-config.checkpoint-interval 500 \
    --training-artifacts-config.validation-interval 200 \
    --training-artifacts-config.n-batches-per-validation 100

echo "Training ends at $(date)"
