import logging

logging_level = logging.INFO
logging.basicConfig(
    level=logging_level, format="%(asctime)s - %(levelname)s - %(message)s"
)

import torch
from dataclasses import dataclass
from pathlib import Path

from poseforge.pose_estimation.data import init_atomic_dataset_and_dataloader
from poseforge.pose_estimation.feature_extractor import ResNetFeatureExtractor
from poseforge.pose_estimation.contrast import (
    ContrastivePretrainingPipeline,
    ContrastiveProjectionHead,
)
from poseforge.util import set_random_seed, get_hardware_availability


@dataclass
class SamplingConfig:
    # Numbers of samples (frames) in each pre-extracted atomic batch
    atomic_batch_nsamples: int
    # Number of variants (synthetic images made by different style transfer models)
    atomic_batch_nvariants: int
    # Number of different frames to include in each batch. Note that n_variants variants
    # of each frame will be included, so effective batch size =
    # train_batch_size * n_variants.
    # This must be a multiple of `atomic_epoch_nsamples` in `AtomicBatchDataset`.
    train_batch_size: int
    # Validation batch size. Can be much smaller than train_batch_size. Must be
    # a multiple of `atomic_epoch_nsamples` in `AtomicBatchDataset`
    val_batch_size: int = 128
    # Number of workers for data loading. Use number of CPU cores if None.
    num_workers: int | None = None


@dataclass
class ModelConfig:
    # Whether to use pretrained weights for the feature extractor, or just use the
    # architecture with random initialization
    use_pretrained_backbone: bool = True
    # Number of hidden dimensions in the contrastive projection head (3-layer MLP)
    projection_head_hidden_dim: int = 512
    # Number of output dimensions in the contrastive projection head (3-layer MLP)
    projection_head_output_dim: int = 256


@dataclass
class DataConfig:
    # Paths to training data (recursively containing atomic batches)
    train_data_dirs: list[str]
    # Paths to validation data (recursively containing atomic batches)
    val_data_dirs: list[str]
    # Frame size (height, width)
    image_size: tuple[int, int] = (256, 256)
    # Number of channels in input images (3 to use pretrained ResNet weights)
    num_channels: int = 3


@dataclass
class TrainingConfig:
    # Total number of epochs to train for
    num_epochs: int
    # Random seed for reproducibility
    seed: int = 42
    # Learning rate for Adam optimizer
    adam_lr: float = 3e-4
    # Weight decay for Adam optimizer
    adam_weight_decay: float = 1e-4


@dataclass
class OutputConfig:
    # Base directory to save logs and model checkpoints
    output_basedir: str
    # Log training metrics every N steps
    logging_interval: int = 10
    # Save model checkpoint every N steps (NOT EPOCHS!)
    checkpoint_interval: int = 500
    # Run validation every N steps (NOT EPOCHS!)
    validation_interval: int = 500
    # Number of batches to use for each validation (useful if validation set is large)
    nbatches_per_validation: int = 300


@dataclass
class Config:
    sampling: SamplingConfig
    model: ModelConfig
    data: DataConfig
    training: TrainingConfig
    output: OutputConfig


def pretrain_contrastive_model(
    sampling: SamplingConfig,
    model: ModelConfig,
    data: DataConfig,
    training: TrainingConfig,
    output: OutputConfig,
) -> None:
    """Pretrain a contrastive representation learning model using synthetic images
    generated by style transfer models."""
    # System setup
    set_random_seed(training.seed)
    hardware_avail = get_hardware_availability(check_gpu=True, print_results=True)
    if len(hardware_avail["gpus"]) == 0:
        raise RuntimeError("No GPU available for training")
    torch.backends.cudnn.benchmark = True

    # Initialize datasets and dataloaders
    train_ds, train_loader = init_atomic_dataset_and_dataloader(
        data_dirs=data.train_data_dirs,
        atomic_batch_nsamples=sampling.atomic_batch_nsamples,
        atomic_batch_nvariants=sampling.atomic_batch_nvariants,
        image_size=data.image_size,
        batch_size=sampling.train_batch_size,
        num_workers=sampling.num_workers,
        num_channels=3,
    )
    val_ds, val_loader = init_atomic_dataset_and_dataloader(
        data_dirs=data.val_data_dirs,
        atomic_batch_nsamples=sampling.atomic_batch_nsamples,
        atomic_batch_nvariants=sampling.atomic_batch_nvariants,
        image_size=data.image_size,
        batch_size=sampling.val_batch_size,
        num_workers=sampling.num_workers,
        num_channels=3,
    )

    # Initialize models
    feature_extractor = ResNetFeatureExtractor(
        weights="IMAGENET1K_V1" if model.use_pretrained_backbone else None
    )
    logging.info("Created feature extractor")
    # Extractor output is global-pooled to 1x1 (see ContrastivePretrainingPipeline)
    projection_head_input_dim = feature_extractor.output_channels * 1 * 1
    projection_head = ContrastiveProjectionHead(
        input_dim=projection_head_input_dim,
        hidden_dim=model.projection_head_hidden_dim,
        output_dim=model.projection_head_output_dim,
    )
    logging.info("Created projection head")

    # Initialize contrastive learning pipeline
    pipeline = ContrastivePretrainingPipeline(
        feature_extractor=feature_extractor,
        projection_head=projection_head,
        device="cuda",
        use_float16=True,
    )

    # Train models
    adam_optimizer_kwargs = {
        "lr": training.adam_lr,
        "weight_decay": training.adam_weight_decay,
    }
    log_dir = Path(output.output_basedir) / "logs"
    checkpoint_dir = Path(output.output_basedir) / "checkpoints"
    pipeline.train(
        training_data_loader=train_loader,
        validation_data_loader=val_loader,
        num_epochs=training.num_epochs,
        adam_kwargs=adam_optimizer_kwargs,
        log_dir=log_dir,
        log_interval=output.logging_interval,
        checkpoint_dir=checkpoint_dir,
        checkpoint_interval=output.checkpoint_interval,
        validation_interval=output.validation_interval,
        nbatches_per_validation=output.nbatches_per_validation,
    )


if __name__ == "__main__":
    import tyro

    tyro.cli(
        pretrain_contrastive_model,
        prog=f"python {Path(__file__).name}",
        description="Pretrain a ResNet feature extractor using a contrastive loss on synthetic videos.",
    )

    # Example CLI command to run this script:
    # python -u src/poseforge/pose_estimation/scripts/run_contrastive_pretraining.py \
    #     --sampling.atomic-batch-nsamples 32 \
    #     --sampling.atomic-batch-nvariants 4 \
    #     --sampling.train-batch-size 96 \
    #     --sampling.val-batch-size 96 \
    #     --sampling.num-workers 4 \
    #     --model.use-pretrained-backbone \
    #     --model.projection-head-hidden-dim 512 \
    #     --model.projection-head-output-dim 256 \
    #     --data.train-data-dirs \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial005" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial005" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial005" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial005" \
    #     --data.val-data-dirs \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
    #     --data.image-size 256 256 \
    #     --data.num-channels 3 \
    #     --training.num-epochs 10 \
    #     --training.seed 42 \
    #     --training.adam-lr 3e-4 \
    #     --training.adam-weight-decay 1e-4 \
    #     --output.output-basedir \
    #         "bulk_data/pose_estimation/contrastive_pretraining/trial_with_cli" \
    #     --output.logging-interval 10 \
    #     --output.checkpoint-interval 500 \
    #     --output.validation-interval 500 \
    #     --output.nbatches-per-validation 300

    # Example usage by calling the function directly (no CLI)
    # sampling_config = SamplingConfig(
    #     atomic_batch_nsamples=32,
    #     atomic_batch_nvariants=4,
    #     train_batch_size=96,  # batch_size 96 -> ~8.25 GB GPU memory with n_variants=4
    #     val_batch_size=96,
    #     num_workers=4,
    # )
    # model_config = ModelConfig(
    #     use_pretrained_backbone=True,
    #     projection_head_hidden_dim=512,
    #     projection_head_output_dim=256,
    # )
    # data_basedir = Path("bulk_data/pose_estimation/atomic_batches")
    # train_data_dirs = [
    #     data_basedir / f"BO_Gal4_fly{fly}_trial{trial:03d}"
    #     for fly in range(1, 5)  # flies 1-4
    #     for trial in range(1, 6)  # trials 1-5
    # ]
    # val_data_dirs = [data_basedir / f"BO_Gal4_fly1_trial001"]
    # data_config = DataConfig(
    #     train_data_dirs=[str(path) for path in train_data_dirs],
    #     val_data_dirs=[str(path) for path in val_data_dirs],
    #     image_size=(256, 256),
    #     num_channels=3,
    # )
    # training_config = TrainingConfig(
    #     num_epochs=10,
    #     seed=42,
    #     adam_lr=3e-4,
    #     adam_weight_decay=1e-4,
    # )
    # output_config = OutputConfig(
    #     output_basedir="bulk_data/pose_estimation/contrastive_pretraining/trial0",
    #     logging_interval=10,
    #     checkpoint_interval=50,
    #     validation_interval=50,
    #     nbatches_per_validation=30,
    # )
    # pretrain_contrastive_model(
    #     sampling=sampling_config,
    #     model=model_config,
    #     data=data_config,
    #     training=training_config,
    #     output=output_config,
    # )
