flip_detection:
  checkpoint: "/home/stimpfling/poseforge/production_models/flip_detection/flip_detection_model/best_model.pth"

# Common settings shared between bodyseg and keypoints3d inference scripts
common:
  n_workers: 16
  inference_image_size: [900, 900]
  # class_labels: ["Background", 'LFCoxa', 'LFFemur', 'LFTibia',
  #      'LMCoxa', 'LMFemur', 'LMTibia',
  #      'LHCoxa', 'LHFemur', 'LHTibia',
  #      'RFCoxa', 'RFFemur', 'RFTibia',
  #      'RMCoxa', 'RMFemur', 'RMTibia',
  #      'RHCoxa', 'RHFemur', 'RHTibia']
  class_labels: ['Background', 'LFFemur', 'LFTibia',
         'LMFemur', 'LMTibia',
         'LHFemur', 'LHTibia',
         'RFFemur', 'RFTibia',
         'RMFemur', 'RMTibia',
         'RHFemur', 'RHTibia']
bodyseg:
  checkpoint: "/Volumes/upramdya/data/VAS/poseforge/production/pose_estimation/bodyseg/output_20260507_tiled_nocoxa/checkpoints/epoch29_step1000.model.pth"
  batch_size: 16
  output_buffer_log_interval: 10

keypoints3d:
  checkpoint: "/Volumes/upramdya/data/VAS/poseforge/production/pose_estimation/keypoints3d/trial_20260507_tiled/checkpoints/epoch19_step2039.model.pth"
  batch_size: 32
  camera_pos: [0.0, 0.0, -67.0]
  camera_fov_deg: 5.0
  camera_rendering_size: [900, 900]
  camera_rotation_euler: [0, 3.14159265359, -1.57079632679]