import logging

logging_level = logging.INFO
logging.basicConfig(
    level=logging_level, format="%(asctime)s - %(levelname)s - %(message)s"
)

import torch
from pathlib import Path
from torchsummary import summary

import poseforge.pose_estimation.contrast.config as config
from poseforge.pose_estimation.contrast import (
    ContrastivePretrainingPipeline,
    ContrastivePretrainingModel,
    InfoNCELoss,
)
from poseforge.pose_estimation.data.synthetic import init_atomic_dataset_and_dataloader
from poseforge.pose_estimation.feature_extractor import ResNetFeatureExtractor
from poseforge.util import set_random_seed, get_hardware_availability


def pretrain_contrastive_model(
    n_epochs: int,
    model_architecture_config: config.ModelArchitectureConfig,
    model_weights_config: config.ModelWeightsConfig,
    loss_config: config.LossConfig,
    training_data_config: config.TrainingDataConfig,
    optimizer_config: config.OptimizerConfig,
    training_artifacts_config: config.TrainingArtifactsConfig,
    seed: int = 42,
) -> None:
    """Pretrain a contrastive representation learning model using synthetic images
    generated by style transfer models."""
    # System setup
    set_random_seed(seed)
    hardware_avail = get_hardware_availability(check_gpu=True, print_results=True)
    if len(hardware_avail["gpus"]) == 0:
        raise RuntimeError("No GPU available for training")
    torch.backends.cudnn.benchmark = True

    # Save configs
    configs_dir = Path(training_artifacts_config.output_basedir) / "configs"
    configs_dir.mkdir(parents=True, exist_ok=True)
    model_architecture_config.save(configs_dir / "model_architecture_config.yaml")
    if model_weights_config is not None:
        model_weights_config.save(configs_dir / "model_weights_config.yaml")
    loss_config.save(configs_dir / "loss_config.yaml")
    training_data_config.save(configs_dir / "data_config.yaml")
    optimizer_config.save(configs_dir / "optimizer_config.yaml")
    training_artifacts_config.save(configs_dir / "artifacts_config.yaml")

    # Initialize datasets and dataloaders
    train_ds, train_loader = init_atomic_dataset_and_dataloader(
        data_dirs=training_data_config.train_data_dirs,
        atomic_batch_n_samples=training_data_config.atomic_batch_n_samples,
        atomic_batch_n_variants=training_data_config.atomic_batch_n_variants,
        input_image_size=training_data_config.image_size,
        batch_size=training_data_config.train_batch_size,
        n_workers=training_data_config.n_workers,
        n_channels=3,
        prefetch_factor=2,
    )
    val_ds, val_loader = init_atomic_dataset_and_dataloader(
        data_dirs=training_data_config.val_data_dirs,
        atomic_batch_n_samples=training_data_config.atomic_batch_n_samples,
        atomic_batch_n_variants=training_data_config.atomic_batch_n_variants,
        input_image_size=training_data_config.image_size,
        batch_size=training_data_config.val_batch_size,
        n_workers=training_data_config.n_workers,
        n_channels=3,
        prefetch_factor=2,
    )

    # Initialize models
    model = ContrastivePretrainingModel.create_architecture_from_config(
        architecture_config=model_architecture_config
    )
    model.load_weights_from_config(weights_config=model_weights_config)
    feature_extractor = model.feature_extractor
    projection_head = model.projection_head
    print("========== Feature Extractor Summary ==========")
    summary(feature_extractor.cuda(), (3, *training_data_config.image_size))
    print("=========== Projection Head Summary ===========")
    summary(projection_head.cuda(), (model.feature_extractor.output_channels,))

    # Initialize InfoNCE loss function
    info_nce_loss_func = InfoNCELoss.create_from_config(loss_config)

    # Initialize contrastive learning pipeline
    pipeline = ContrastivePretrainingPipeline(
        contrastive_pretraining_model=model,
        info_nce_loss_func=info_nce_loss_func,
        device="cuda",
        use_float16=True,
    )

    # Train models
    adam_optimizer_kwargs = {
        "lr": optimizer_config.adam_lr,
        "weight_decay": optimizer_config.adam_weight_decay,
    }
    log_dir = Path(training_artifacts_config.output_basedir) / "logs"
    checkpoint_dir = Path(training_artifacts_config.output_basedir) / "checkpoints"
    pipeline.train(
        training_data_loader=train_loader,
        validation_data_loader=val_loader,
        num_epochs=n_epochs,
        adam_kwargs=adam_optimizer_kwargs,
        log_dir=log_dir,
        log_interval=training_artifacts_config.logging_interval,
        checkpoint_dir=checkpoint_dir,
        checkpoint_interval=training_artifacts_config.checkpoint_interval,
        validation_interval=training_artifacts_config.validation_interval,
        nbatches_per_validation=training_artifacts_config.n_batches_per_validation,
    )


if __name__ == "__main__":
    import tyro

    tyro.cli(
        pretrain_contrastive_model,
        prog=f"python {Path(__file__).name}",
        description="Pretrain a ResNet feature extractor using a contrastive loss on synthetic videos.",
    )

    # Example CLI command to run this script:
    # python -u src/poseforge/pose_estimation/contrast/scripts/run_contrastive_pretraining.py \
    #     --n-epochs 10 \
    #     --seed 42 \
    #     --model-architecture-config.projection-head-hidden-dim 512 \
    #     --model-architecture-config.projection-head-output-dim 256 \
    #     --model-weights-config.feature-extractor-weights "IMAGENET1K_V1" \
    #     --loss-config.info-nce-temperature 0.1 \
    #     --training-data-config.train-data-dirs \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial005" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly2_trial005" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly3_trial005" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial001" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial002" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial003" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial004" \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly4_trial005" \
    #     --training-data-config.val-data-dirs \
    #         "bulk_data/pose_estimation/atomic_batches/BO_Gal4_fly1_trial001" \
    #     --training-data-config.atomic-batch-n-samples 32 \
    #     --training-data-config.atomic-batch-n-variants 4 \
    #     --training-data-config.train-batch-size 96 \
    #     --training-data-config.val-batch-size 96 \
    #     --training-data-config.image-size 256 256 \
    #     --training-data-config.n-workers 8 \
    #     --optimizer-config.adam-lr 3e-4 \
    #     --optimizer-config.adam-weight-decay 1e-4 \
    #     --training-artifacts-config.output-basedir \
    #         "bulk_data/pose_estimation/contrastive_pretraining/trial_with_cli" \
    #     --training-artifacts-config.logging-interval 10 \
    #     --training-artifacts-config.checkpoint-interval 50 \
    #     --training-artifacts-config.validation-interval 50 \
    #     --training-artifacts-config.n-batches-per-validation 30

    # Example usage by calling the function directly (no CLI)
    # model_architecture_config = config.ModelArchitectureConfig(
    #     projection_head_hidden_dim=512, projection_head_output_dim=256
    # )
    # model_weights_config = config.ModelWeightsConfig(
    #     feature_extractor_weights="IMAGENET1K_V1"
    # )
    # loss_config = config.LossConfig(info_nce_temperature=0.1)
    # data_basedir = Path("bulk_data/pose_estimation/atomic_batches")
    # train_data_dirs = [
    #     data_basedir / f"BO_Gal4_fly{fly}_trial{trial:03d}"
    #     for fly in range(1, 5)  # flies 1-4
    #     for trial in range(1, 6)  # trials 1-5
    # ]
    # val_data_dirs = [data_basedir / f"BO_Gal4_fly1_trial001"]
    # training_data_config = config.TrainingDataConfig(
    #     train_data_dirs=[str(path) for path in train_data_dirs],
    #     val_data_dirs=[str(path) for path in val_data_dirs],
    #     atomic_batch_n_samples=32,
    #     atomic_batch_n_variants=4,
    #     train_batch_size=96,  # batch_size 96 -> ~8.25 GB GPU memory with n_variants=4
    #     val_batch_size=96,
    #     image_size=(256, 256),
    #     n_workers=8,
    # )
    # optimizer_config = config.OptimizerConfig(adam_lr=3e-4, adam_weight_decay=1e-4)
    # training_artifacts_config = config.TrainingArtifactsConfig(
    #     output_basedir="bulk_data/pose_estimation/contrastive_pretraining/trial0",
    #     logging_interval=10,
    #     checkpoint_interval=50,
    #     validation_interval=50,
    #     n_batches_per_validation=30,
    # )
    # pretrain_contrastive_model(
    #     n_epochs=10,
    #     model_architecture_config=model_architecture_config,
    #     model_weights_config=model_weights_config,
    #     loss_config=loss_config,
    #     training_data_config=training_data_config,
    #     optimizer_config=optimizer_config,
    #     training_artifacts_config=training_artifacts_config,
    #     seed=42,
    # )
