#!/bin/bash -l

#SBATCH --job-name contrastive-repr-inference-fly<<<FLY>>>
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 8
#SBATCH --mem 45GB
#SBATCH --time 24:00:00
#SBATCH --partition=l40s
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --output <<<STDOUT_STDERR_FILE>>>

echo "Hello from $(hostname)"

# Set up environment and package
. ~/spack/share/spack/setup-env.sh
spack load ffmpeg
conda activate poseforge

# Define paths
# Edit these in the script for your cluster layout.
project_root="/home/$USER/poseforge"
style_transfer_root="/work/upramdya/stimpfli/poseforge/style_transfer/production/tiled_translated_videos/flybody_gray"
contrastive_pretraining_root="/scratch/stimpfli/poseforge/style_transfer/contrastive_pretraining"
contrastive_pretraining_trial="trial_20260607_256_tiled2variants"

# Setup
cd $project_root

# Training
echo "Start running inference at $(date)"

python -u src/poseforge/pose/contrast/scripts/run_feature_extractor_inference.py \
    --batch-size 256 \
    --training-stages \
        "untrained" \
        "epoch000_step000500" \
        "epoch001_step000500" \
        "epoch003_step000500" \
        "epoch005_step000500" \
        "epoch007_step000500" \
        "epoch009_step000500" \
    --pretraining_model_dir \
        "$contrastive_pretraining_root/$contrastive_pretraining_trial" \
    --synthetic_videos_basedir "$style_transfer_root" \
    --synthetic-videos-subdirs \
        "$style_transfer_root/BO_Gal4_fly<<<FLY>>>_trial001" \
        "$style_transfer_root/BO_Gal4_fly<<<FLY>>>_trial002" \
        "$style_transfer_root/BO_Gal4_fly<<<FLY>>>_trial003" \
        "$style_transfer_root/BO_Gal4_fly<<<FLY>>>_trial004" \
        "$style_transfer_root/BO_Gal4_fly<<<FLY>>>_trial005" \
    --style-transfer-models \
        "20260425_082136_lamG01_bs4_ngf322_flybody_gray_epoch665" \
        "20260425_082136_lamG01_bs4_ngf322_flybody_gray_epoch750" \
        "20260425_082309_lamG02_bs4_ngf16_flybody_gray_epoch831" \
        "20260425_082309_lamG02_bs4_ngf16_flybody_gray_epoch961" \
        "20260425_082346_lamG1_bs4_ngf32_flybody_gray_epoch609" \
        "20260425_082346_lamG1_bs4_ngf32_flybody_gray_epoch991" \
        "20260425_082514_lamG01_bs4_ngf48_flybody_gray_epoch334" \
        "20260425_082514_lamG01_bs4_ngf48_flybody_gray_epoch788" \

echo "Inference ends at $(date)"
