import logging

logging_level = logging.INFO
logging.basicConfig(
    level=logging_level, format="%(asctime)s - %(levelname)s - %(message)s"
)

import torch
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from biomechpose.pose_estimation.data import SimulatedDataSequence
from biomechpose.pose_estimation.feature_extractor import ResNetFeatureExtractor
from biomechpose.pose_estimation.keypoints_3d import (
    Pose2p5DModel,
    Pose2p5DLoss,
    Pose2p5DPipeline,
)
from biomechpose.util import set_random_seed, get_hardware_availability


@dataclass
class SamplingConfig:
    # Numbers of samples (frames) in each pre-extracted atomic batch
    atomic_batch_nsamples: int
    # Number of variants (synthetic images made by different style transfer models)
    atomic_batch_nvariants: int
    # Number of different frames to include in each batch. Note that n_variants variants
    # of each frame will be included, so effective batch size =
    # train_batch_size * n_variants.
    # This must be a multiple of `atomic_epoch_nsamples` in `AtomicBatchDataset`.
    train_batch_size: int
    # Validation batch size. Can be much smaller than train_batch_size. Must be
    # a multiple of `atomic_epoch_nsamples` in `AtomicBatchDataset`
    val_batch_size: int = 128
    # Number of workers for data loading. Use number of CPU cores if None.
    num_workers: int | None = None


@dataclass
class ModelConfig:
    # Feature extractor weights. Can be a path to the (contrastively) pretrained weights
    # or "IMAGENET1K_V1"
    feature_extractor_weights: str
    # Model weights, optional. If provided, the model will be initialized from these
    # weights (in which case feature_extractor_weights is ignored).
    model_weights: str | None = None
    # Number of hidden dimensions in the contrastive projection head (3-layer MLP)
    projection_head_hidden_dim: int = 512
    # Number of output dimensions in the contrastive projection head (3-layer MLP)
    projection_head_output_dim: int = 256
    # Number of body keypoints to detect
    n_keypoints: int = 32
    # Number of bins to quantize depth values (distances from camera) into
    depth_n_bins: int = 64
    # Minimum depth (distance from camera) in mm
    depth_min: float = -2.0
    # Maximum depth (distance from camera) in mm
    depth_max: float = 2.0
    # Temperature param to regulate the "softness" of the predicted x-y heatmaps
    xy_temperature: float = 0.8
    # Temperature param to regulate the "softness" of the predicted depth distributions
    depth_temperature: float = 0.8
    # Number of layers in the core upsampling pathway of the 3D pose estimation model
    upsample_n_layers: int = 3
    # Number of hidden channels in each deconv layer in the core upsampling pathway
    upsample_n_hidden_channels: int = 256
    # Number of hidden channels in the head that predicts depth distributions
    depth_n_hidden_channels: int = 256
    # Method to compute confidence scores from predicted distr ("entropy" for entropy
    # over predicted distr, "peak" for highest predicted probability in the distr)
    confidence_method: str = "entropy"
    # Number of groups in GroupNorm layers
    groupnorm_n_groups: int = 32
    # Std dev for initializing of final layers in x-y and depth heads (no ReLU after)
    pose_head_init_std: float = 1e-3


@dataclass
class LossConfig:
    # Loss function for x-y heatmaps ("mse" for simple mean squared error between
    # predicted and target heatmaps, "kl" for KL divergence between predicted and
    # target heatmaps treated as probability distributions)
    heatmap_loss_func: str = "kl"
    # Std dev (in heatmap pixels) of Gaussian used to generate target x-y heatmaps. Note
    # that a pixel on the heatmap may correspond to multiple pixels in the input image.
    heatmap_sigma: float = 2.0
    # Std dev (in depth bins) of Gaussian used to generate soft target depth distr
    depth_sigma_bins: float = 1.0
    # Weight for x-y heatmap loss term
    xy_loss_weight: float = 4.0
    # Weight for depth cross-entropy loss term
    depth_ce_loss_weight: float = 1.0
    # Weight for depth L1 loss term
    depth_l1_loss_weight: float = 0.25
    # Whether to clamp predicted depth values to be within [depth_min, depth_max]
    # (a warning will always be issued if predicted depths are out of bounds)
    clamp_labels: bool = True


@dataclass
class DataConfig:
    # Style transfer models (including epochs) to use
    style_transfer_models: list[str]
    # Root directory to synthetic videos generated by style transfer models. This is
    # expected to contain the following file structure:
    # {exp_trial}/segment_{segid}/subsegment_{subsegid}/translated_{model}.mp4
    synthetic_videos_basedir: str
    # Subdirectories to synthetic videos, in case we don't want to process all of them.
    # These must be directories under synthetic_videos_basedir.
    # If None, process all data.
    synthetic_videos_subdirs: list[str] | None = None
    # Frame size (height, width)
    image_size: tuple[int, int] = (256, 256)
    # Base depth of all keypoints in mm. The model will predict the relative depth, i.e.
    # depth_label - base_depth, instead of the absolute depth.
    depth_offset: float = -100.0


@dataclass
class TrainingConfig:
    # Total number of epochs to train for
    num_epochs: int
    # Random seed for reproducibility
    seed: int = 42
    # Learning rate for Adam optimizer
    adam_lr: float = 3e-4
    # Weight decay for Adam optimizer
    adam_weight_decay: float = 1e-4


@dataclass
class OutputConfig:
    # Base directory to save logs and model checkpoints
    output_basedir: str
    # Log training metrics every N steps
    logging_interval: int = 10
    # Save model checkpoint every N steps (NOT EPOCHS!)
    checkpoint_interval: int = 500
    # Run validation every N steps (NOT EPOCHS!)
    validation_interval: int = 500
    # Number of batches to use for each validation (useful if validation set is large)
    nbatches_per_validation: int = 300


def _init_model_from_config(
    feature_extractor: ResNetFeatureExtractor, model_config: ModelConfig
) -> Pose2p5DModel:
    model = Pose2p5DModel(
        n_keypoints=model_config.n_keypoints,
        feature_extractor=feature_extractor,
        depth_n_bins=model_config.depth_n_bins,
        depth_min=model_config.depth_min,
        depth_max=model_config.depth_max,
        xy_temperature=model_config.xy_temperature,
        depth_temperature=model_config.depth_temperature,
        upsample_n_layers=model_config.upsample_n_layers,
        upsample_n_hidden_channels=model_config.upsample_n_hidden_channels,
        depth_n_hidden_channels=model_config.depth_n_hidden_channels,
        confidence_method=model_config.confidence_method,
        groupnorm_n_groups=model_config.groupnorm_n_groups,
        pose_head_init_std=model_config.pose_head_init_std,
    )
    logging.info("Created 2.5D pose estimation model")
    return model


def _setup_model(model_config: ModelConfig) -> Pose2p5DModel:
    # If full model weights are provided, load them directly
    if model_config.model_weights is not None:
        checkpoint_path = Path(model_config.model_weights)
        if not checkpoint_path.is_file():
            raise ValueError(f"Model weights path {checkpoint_path} is not a file")
        weights = torch.load(checkpoint_path, map_location="cpu")
        feature_extractor = ResNetFeatureExtractor(weights=None)
        model = _init_model_from_config(feature_extractor, model_config)
        model.load_state_dict(weights["model"])
        logging.info(f"Set up model using weights from {checkpoint_path}")
        return model

    # Otherwise, init feature extractor first
    fe_weights_option = model_config.feature_extractor_weights
    if fe_weights_option == "IMAGENET1K_V1":
        feature_extractor = ResNetFeatureExtractor(weights=fe_weights_option)
        logging.info(f"Created feature extractor using {fe_weights_option} weights")
    else:
        # Weights must be given as a checkpoint path then
        checkpoint_path = Path(fe_weights_option)
        if not checkpoint_path.is_file():
            raise ValueError(
                f"Feature extractor weights {fe_weights_option} is neither "
                '"IMAGENET1K_V1" nor a valid path'
            )
        feature_extractor = ResNetFeatureExtractor(weights=None)
        weights = torch.load(checkpoint_path, map_location="cpu")
        feature_extractor.load_state_dict(weights)
        logging.info(f"Created feature extractor using weights from {checkpoint_path}")
    model = _init_model_from_config(feature_extractor, model_config)
    logging.info("Set up model, incorporating feature extractor above")
    return model


def _setup_loss_func(loss_config: LossConfig) -> Pose2p5DLoss:
    loss_func = Pose2p5DLoss(**loss_config.__dict__)
    logging.info("Set up 2.5D pose estimation loss function")
    return loss_func


def _init_simulated_data_sequence_datasets(
    style_transfer_models: list[str],
    synthetic_videos_basedir: Path | str,
    synthetic_videos_subdirs: list[Path | str] | None,
):
    synthetic_videos_basedir = Path(synthetic_videos_basedir)

    # Find all simulations to process
    if synthetic_videos_subdirs is None:
        synthetic_videos_subdirs = list(synthetic_videos_basedir.glob("*"))
    else:
        synthetic_videos_subdirs = [Path(subdir) for subdir in synthetic_videos_subdirs]
    simulations_to_use = []
    for subdir in synthetic_videos_subdirs:
        for path in subdir.rglob(f"translated_{style_transfer_models[0]}.mp4"):
            # sim_info: (exp_trial, segment, subsegment)
            sim_info = path.absolute().parent.parts[-3:]
            simulations_to_use.append(sim_info)

    # Create dataset objects based on identified files
    datasets = []
    for exp_trial, segment, subsegment in sorted(simulations_to_use):
        sim_name = f"{exp_trial}/{segment}/{subsegment}"
        synthetic_video_paths = [
            synthetic_videos_basedir / sim_name / f"translated_{model}.mp4"
            for model in style_transfer_models
        ]
        simulated_label_path = (
            Path("bulk_data/nmf_rendering") / sim_name / "processed_simulation_data.h5"
        )
        
        dataset = SimulatedDataSequence(
            synthetic_video_paths,
            simulated_labels_path=simulated_label_path,
            sim_name=sim_name,
            original_image_size=(464, 464), # TODO
        )
        datasets.append(dataset)

    return datasets


def run_inference_on_simulated_data_sequence(
    pipeline: Pose2p5DPipeline, data_sequence: SimulatedDataSequence, batch_size: int
):
    n_variants = 8  # TODO
    all_predictions = defaultdict(list)
    all_labels = defaultdict(list)
    for frames, labels in data_sequence.generate_batches(batch_size):
        pred_dict = pipeline.inference(frames)
        n_frames = frames.shape[0] // n_variants
        for key, value in pred_dict.items():
            if isinstance(value, torch.Tensor):
                # Reshape back to separate variants and frames
                # value: (n_variants * n_frames, ...)
                # -> (n_variants, n_frames, ...)
                value = value.view(n_variants, n_frames, *value.shape[1:])
            all_predictions[key].append(value)
        for key, value in labels.items():
            all_labels[key].append(value)

    for key in all_predictions:
        if isinstance(all_predictions[key][0], torch.Tensor):
            all_predictions[key] = torch.cat(all_predictions[key], dim=1)  # 0 for variants, 1 for frames
    for key in all_labels:
        if isinstance(all_labels[key][0], torch.Tensor):
            all_labels[key] = torch.cat(all_labels[key], dim=0)

    return all_predictions, all_labels


def test_keypoints3d_model(
    model: ModelConfig,
    loss: LossConfig,
    data: DataConfig,
    output: OutputConfig,
) -> None:
    """Train the 3D keypoint detection model using a pretrained feature extractor."""
    # System setup
    set_random_seed(42)  # TODO
    hardware_avail = get_hardware_availability(check_gpu=True, print_results=True)
    if len(hardware_avail["gpus"]) == 0:
        raise RuntimeError("No GPU available for training")
    torch.backends.cudnn.benchmark = True

    # Initialize datasets
    datasets = _init_simulated_data_sequence_datasets(
        style_transfer_models=data.style_transfer_models,
        synthetic_videos_basedir=data.synthetic_videos_basedir,
        synthetic_videos_subdirs=data.synthetic_videos_subdirs,
    )

    # Initialize model and loss function
    pose_model = _setup_model(model)  # `model` argument is actually ModelConfig
    criterion = _setup_loss_func(loss)  # `loss` is actually LossConfig

    # Initialize learning pipeline
    pipeline = Pose2p5DPipeline(
        model=pose_model,
        loss_func=criterion,
        depth_offset=data.depth_offset,
        device="cuda",
        use_float16=True,
    )

    # Train the model
    # log_dir = Path(output.output_basedir) / "logs"
    # checkpoint_dir = Path(output.output_basedir) / "checkpoints"
    preds, labels = run_inference_on_simulated_data_sequence(
        pipeline=pipeline, data_sequence=datasets[0], batch_size=128
    )
    # preds_xy = preds["pred_xy"]
    # preds_depth = preds["pred_depth"]
    # labels_xy = labels["keypoint_pos"][:, :, :2]
    # labels_depth = labels["keypoint_pos"][:, :, 2] - data.depth_offset
    
    import matplotlib.pyplot as plt
    n_variants = 8
    n_keypoints = 32
    fig, axes = plt.subplots(n_keypoints, 3, figsize=(6, 64), tight_layout=True)
    for keypoint_idx in range(n_keypoints):
        for dim_idx, dim in enumerate(["x", "y", "depth"]):
            ax = axes[keypoint_idx, dim_idx]
            label_vals = labels["keypoint_pos"][:, keypoint_idx, dim_idx]
            if dim == "depth":
                label_vals = label_vals - data.depth_offset
            x_grid = torch.arange(preds["pred_depth"].shape[1])  # frame indices
            for variant_idx in range(n_variants):
                if dim in ["x", "y"]:
                    pred_vals = preds["pred_xy"][variant_idx, :, keypoint_idx, dim_idx]
                else:
                    pred_vals = preds["pred_depth"][variant_idx, :, keypoint_idx]
                ax.plot(x_grid, pred_vals.cpu(), linewidth=1)
            ax.plot(x_grid, label_vals.cpu(), linewidth=2, color="black")
    fig.savefig("test_keypoints3d_predictions.png")
    plt.close(fig)

    logging.info("Inference complete")


if __name__ == "__main__":
    import tyro

    # args = tyro.cli(
    #     train_keypoints3d_model,
    #     prog=f"python {Path(__file__).name}",
    #     description="Train a 3D keypoint detection model using pretrained feature extractor.",
    # )

    pretraining_trial_dir = Path(
        "bulk_data/pose_estimation/contrastive_pretraining/trial_20251001a/"
    )
    checkpoint_to_use = (
        pretraining_trial_dir
        / "checkpoints/checkpoint_epoch009_step003000.feature_extractor.pth"
    )
    model_config = ModelConfig(
        feature_extractor_weights=None,  # str(checkpoint_to_use),
        model_weights="bulk_data/pose_estimation/keypoints3d/trial_20250103a/checkpoints/epoch9_step52000.pt",
        projection_head_hidden_dim=512,
        projection_head_output_dim=256,
        n_keypoints=32,
        depth_n_bins=64,
        depth_min=-2.0,
        depth_max=2.0,
        xy_temperature=0.8,
        depth_temperature=0.8,
        upsample_n_layers=3,
        upsample_n_hidden_channels=256,
        depth_n_hidden_channels=256,
        confidence_method="entropy",
        groupnorm_n_groups=32,
        pose_head_init_std=1e-3,
    )
    loss_config = LossConfig(
        heatmap_loss_func="kl",
        heatmap_sigma=2.0,
        depth_sigma_bins=1.0,
        xy_loss_weight=4.0,
        depth_ce_loss_weight=1.0,
        depth_l1_loss_weight=0.25,
        clamp_labels=True,
    )
    style_transfer_models = [
        "ngf16_netGsmallstylegan2_batsize2_lambGAN0.2_epoch121",
        "ngf16_netGstylegan2_batsize4_lambGAN0.2_epoch200",
        "ngf32_netGstylegan2_batsize2_lambGAN0.5-cont1_epoch161",
        "ngf32_netGstylegan2_batsize4_lambGAN0.1_epoch161",
        "ngf32_netGstylegan2_batsize4_lambGAN0.5_epoch141",
        "ngf32_netGstylegan2_batsize4_lambGAN1.0_epoch161",
        "ngf48_netGstylegan2_batsize2_lambGAN0.1_epoch141",
        "ngf48_netGstylegan2_batsize4_lambGAN0.1_epoch141",
    ]
    data_config = DataConfig(
        style_transfer_models=style_transfer_models,
        synthetic_videos_basedir="bulk_data/style_transfer/production/translated_videos/",
        synthetic_videos_subdirs=[
            "bulk_data/style_transfer/production/translated_videos/BO_Gal4_fly5_trial005"
        ],
        image_size=(256, 256),
        depth_offset=-100.0,
    )
    output_config = OutputConfig(
        output_basedir="bulk_data/pose_estimation/keypoints3d/trial_20250103a/",
        logging_interval=100,
        checkpoint_interval=1000,
        validation_interval=1000,
        nbatches_per_validation=300,
    )
    test_keypoints3d_model(
        model=model_config, loss=loss_config, data=data_config, output=output_config
    )
